success_indicators_table = {
    11: "Avoid Conflict", 
    12: "Locate Target", 
    13: "Retrieve Item", 
    14: "Protect Asset", 
    15: "Evade Detection", 
    16: "Negotiate Outcome",
    21: "Complete on Schedule", 
    22: "Minimize Damage", 
    23: "Gather Intelligence", 
    24: "Secure Area", 
    25: "Deliver Cargo", 
    26: "Disable Systems",
    31: "Extract Target", 
    32: "No Survivors", 
    33: "Acquire Target", 
    34: "Investigate", 
    35: "Escort Target", 
    36: "Neutralize Threat",
    41: "Maintain Cover", 
    42: "Transmit Information", 
    43: "Repair / Restore", 
    44: "Survey Area", 
    45: "Collect Samples", 
    46: "Destroy Asset",
    51: "Avoid Law / Security", 
    52: "Complete Main Objective", 
    53: "Analyze Data", 
    54: "Coordinate Parties", 
    55: "Contain Hazard", 
    56: "Recover Evidence",
    61: "Reveal Hidden", 
    62: "Maintain Morale", 
    63: "Establish Communication", 
    64: "Adapt to Change", 
    65: "Achieve Objectives", 
    66: "No Casualties"
}

success_levels = [
    {"level": "Routine - A nice-to-have condition; failure has minimal impact on mission success.", "success_value": 2, "failure_value": -2},
    {"level": "Important - Primary Focus of Mission", "success_value": 3, "failure_value": -4},
    {"level": "Critical - Failure could cause mission failure or major fallout.", "success_value": 4, "failure_value": -8},
    {"level": "Paramount - Overrules all other indicators; this must succeed, even at other costs.", "success_value": 5, "failure_value": -12}
]